name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '35 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: 22

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm start
        env:
          GH_LOGIN: ${{ secrets.GH_LOGIN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_LOGIN: ${{ secrets.NPM_LOGIN }}

      - name: Commit changes
        run: |-
          git config user.name "HiDeoo"
          git config user.email "494699+HiDeoo@users.noreply.github.com"
          git add -A
          git commit -m "docs(build): update readme" || exit 0
          git push
